Implement select from list sub-setting
toggl/ios pull request #698
Opened 2020-08-13 16:37 UTC by sofokli1

## Info

### Summary
Adds the sub setting logic and also applies it to the 3 settings that need it. It could be used for the about view as well.

### Relationships
Closes #487
Closes #488
Closes #489
Closes #486

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Go commit by commit and run the app

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑

2020-08-14 09:22 UTC, sofokli1 commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
I do not know if we need it elsewhere. just trying to keep it multi purpose as the `either` one. setting it directly to `firstDayOfTheWeek` and so on, will make it lose its generic nature and be strongly coupled with the settings module. If we keep this kind of approach for navigation we may need this later on if not more of these with even more options available.

as for the delayed population of the tableview. it is because of using the `viewDidAppear` instead of `viewDidLoad`. this is an issue in many other views and it should be fixed at the same times with those (like the main settings view, the main log)

2020-08-14 10:07 UTC, sofokli1 commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
now that i think about it I want to add 2 more options to this since I need to add more settings with the same approach like smart alert and WS selection. You think is better to make it single purpose?

2020-08-14 11:52 UTC, simonrozsival commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
Yep, let's make it single purpose 👍

2020-08-14 11:53 UTC, simonrozsival commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
> as for the delayed population of the tableview. it is because of using the viewDidAppear instead of viewDidLoad. this is an issue in many other views and it should be fixed at the same times with those (like the main settings view, the main log)

Let's add an issue for this (unless there's already one) so that we don't forget to tackle this before we push the app to our users.

2020-08-14 14:08 UTC, dshr commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
+1 to Šimon's comment — this enum is very confusing to read.

2020-08-14 15:54 UTC, sofokli1 commented on Modules/Settings/Settings/Common/View/SubSettingSelectionViewController.swift
> +            // We should do this in ViewDidLoad, but there's a bug that causes an ugly warning. That's why we are doing it here for now
I am not sure and am not touching it for now. will make an issue to deal at a later time with the rest of the instances that do the same thing

2020-08-14 15:55 UTC, sofokli1 commented
@dshr can you be more specific regarding the difference to the UI so that we can see what should be fixed here and what should be fixed elsewhere. otherwise it feels like find the difference game and am not sure what i will miss.
what I see is:
- navigation bar styling
- fonts in the cells could be improved
- the cell separators
- maybe the section footer in the timer section
- the switches will remain as they are (OS default, we are not implementing custom switches)
anything else?

2020-08-14 16:07 UTC, dshr commented
Yeah, and apart from those:
- the nav bar Done button is missing

2020-08-17 13:33 UTC, dshr commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
Actually, now that I'm adding the SendFeedback thing, let's try and use optional state for this, so instead of using `editablePreference`, let's use a custom `MultipleSettingSelectionState` that would take an enum and list it? This way this is going to be in line with the rest of the app

2020-08-17 13:47 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
WS selection is not an enum like the rest of the settings

2020-08-17 13:48 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
I was thinking of using this component to also show the about page

2020-08-17 13:48 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
where the cells are navigation type

2020-08-17 14:13 UTC, dshr commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
> WS selection is not an enum like the rest of the settings
An array of options then? With a `currentlySelectedIndex` prop as well

> I was thinking of using this component to also show the about page
Don't see why not. We're already passing the actions to it, and the impl with the separate state will handle that as well

2020-08-18 09:20 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
@simonrozsival you ok with this ☝️

2020-08-18 09:36 UTC, simonrozsival commented on Modules/Settings/Settings/Common/SettingsState.swift
> +        public var editablePreference: OneOf<DayOfTheWeek, DateFormat, DurationFormat>?
Yep, I'm OK with that 😄

2020-08-18 12:00 UTC, sofokli1 commented on Modules/Settings/Settings/Common/View/SubSettingSelectionViewController.swift
> +            // We should do this in ViewDidLoad, but there's a bug that causes an ugly warning. That's why we are doing it here for now
Ref #702

2020-08-18 12:01 UTC, sofokli1 commented on Modules/Utils/Utils/Either/Either.swift
> +public enum OneOf<A, B, C> {
for the viewDidAppear Ref #702

2020-08-19 08:12 UTC, simonrozsival approved these changes
LGTM

2020-08-19 10:12 UTC, sofokli1 commented
@simonrozsival @dshr  I added some more commits if you want to take a look
main issue that I can not fix in this PR is the back button font. will make an issue fo that, can't look at this PR no more

2020-08-19 12:36 UTC, dshr requested changes
All good, I really like how the settings vc gets reused! One thing though — the dark mode colours could use a bit more love:
<img width="901" alt="Screenshot 2020-08-19 at 15 33 54" src="https://user-images.githubusercontent.com/6031512/90635094-6ab8eb00-e231-11ea-8942-90936ecf63c6.png">
- the nav bar background should be a different colour
- the value labels should have the same colour as the title labels
- the info row label should have the same colour as the value labels have currently

2020-08-20 08:13 UTC, simonrozsival commented
@dshr the settings screen colors don't seem related to this PR's scope and I would suggest moving forward with this PR and creating an issue to revisit the UI in a separate PR.

2020-08-20 08:15 UTC, simonrozsival approved these changes

2020-08-20 08:48 UTC, sofokli1 commented
@dshr 
> the value labels should have the same colour as the title labels

Done

> the nav bar background should be a different colour

Will bundle this with the back button issue

> the info row label should have the same colour as the value labels have currently

this should have the same color as the header label

2020-08-20 08:54 UTC, sofokli1 commented
for navigation bar ref #706

2020-08-20 09:09 UTC, dshr approved these changes
Let's get this 🦑 'd!

2020-08-20 09:40 UTC, merged