Add the submit feedback UI
toggl/ios pull request #703
Opened 2020-08-18 15:02 UTC by dshr

## Info
This PR adds the submit feedback UI and hooks it up to the architecture.

### Relationships
Closes #493

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Commit by commit! There's a weird warning happening after the feedback result snackbar disappears that I couldn't pinpoint — any suggestions are welcome: 
```
Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/desislavhristov/Work/toggl-ios/Pods/RxSwift/RxSwift/Rx.swift:96 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueuing sequence events in some other way.
```

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Go for it!

2020-08-19 07:32 UTC, simonrozsival requested changes
When the snackbar is hidden after the delay, I'm getting this error/warning in the console:

```
>>>>>>>>>>>>>>
Action: MessageEntered: Asd asd Assad’s asd asd asd asd asd
>>>>>>>>>>>>>>
Action: DoneButtonTapped
>>>>>>>>>>>>>>
Action: SetSendFeedbackError The operation couldn’t be completed. (Networking.NetworkingError error 2.)
>>>>>>>>>>>>>>
Action: SendFeedbackResultSeen
>>>>>>>>>>>>>>
⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/simonrozsival/Projects/github/toggl/ios/Pods/RxSwift/RxSwift/Rx.swift:96 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueuing sequence events in some other way.
```

I suppose that shouldn't happen but I'm not sure what exactly causes it (the delayed action is dispatched from a different thread maybe? I can't see any cyclic dependency in the code and sending two actions in parallel could explain why there's a race..)

2020-08-19 12:09 UTC, sofokli1 requested changes
overall looks ok just some small stuff

2020-08-19 12:09 UTC, sofokli1 commented on Modules/Settings/Settings/SubmitFeedback/Views/SubmitFeedbackViewController.swift
> +        let optionMenu = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
canceling without typing should dismiss without action view

2020-08-19 12:32 UTC, sofokli1 commented
also looked into the bug you have but couldn't find why is happening

2020-08-20 08:09 UTC, simonrozsival approved these changes
The console warning/error is gone, the behavior of the screen seems to be working just fine, the UI looks OK.

2020-08-20 08:40 UTC, sofokli1 commented on Modules/Architecture/Architecture/Core/Effect.swift
> -                        subject.onCompleted()
@Odrakir what do you think about this?

2020-08-20 08:53 UTC, dshr commented on Modules/Architecture/Architecture/Core/Effect.swift
> -                        subject.onCompleted()
He's away until the 28th

2020-08-20 09:41 UTC, sofokli1 commented on Modules/Architecture/Architecture/Core/Effect.swift
> -                        subject.onCompleted()
I left this as a placeholder for him to check when he is back

2020-08-20 09:41 UTC, sofokli1 approved these changes

2020-08-20 11:36 UTC, merged