Add more settings
toggl/ios pull request #711
Opened 2020-08-27 14:24 UTC by sofokli1

## Info

### Summary
The smart alert part. is not complete and it is on hold until the feature team agrees on what will happen with it. There is talk of changing it and also move it in the cal settings view. The rest of the issues should work correctly.

### Relationships
Closes #495
Closes #490
Ref #492
Closes #494

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Go commit by commit

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑

2020-08-31 11:41 UTC, Odrakir requested changes

2020-08-31 11:41 UTC, Odrakir commented on Modules/Assets/Assets/Base.lproj/Localizable.strings
> +"Licenses" = "Licenses";
Are there issues to translate these?

2020-08-31 11:41 UTC, Odrakir commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
There's a warning here, we should be using `nil` instead of `.none` in the first case.

2020-08-31 11:41 UTC, Odrakir commented on Modules/Settings/Settings/Common/SettingsState.swift
> +    case defaultWorkspace(Workspace.Identifier?)
Can this ever be nil? 🤔

2020-08-31 11:41 UTC, Odrakir commented on Modules/Models/Models/UserPreferences.swift
> +public enum SmartAlertOption: Equatable {
I think I know where you are coming from, but to me the name was fine as `SmartAlertState`. Then you can have an `allOptions` property instead of `allCases`. What do you think?

2020-08-31 11:41 UTC, Odrakir commented on Podfile
> +    # The following line converts the acknowledgements.markdown to html to show in the the lincens view in app settings
Are you sure this should be in the Podfile? We might ditch Cocoapods at some point losing this and probably not realizing about it.

2020-08-31 12:23 UTC, sofokli1 commented on Modules/Models/Models/UserPreferences.swift
> +public enum SmartAlertOption: Equatable {
I find `SmartAlertState` confusing because of the way we use the word `State` elsewhere. It does not look consistent.
As for `allOptions` I am ok with that change

2020-08-31 12:27 UTC, sofokli1 commented on Podfile
> +    # The following line converts the acknowledgements.markdown to html to show in the the lincens view in app settings
If and when we drop cocopods we should think of an alternative, until then this is fine. This the simplest way for now. If you have an alternative I am all ears.

2020-08-31 12:44 UTC, sofokli1 commented on Modules/Assets/Assets/Base.lproj/Localizable.strings
> +"Licenses" = "Licenses";
ref #715

2020-08-31 13:59 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
without `.none, .some(.none)` xcode complains that switch is not exhaustive

2020-08-31 13:59 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
I see not warning. are using the latests xcode and swiftlinter?

2020-08-31 14:03 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +    case defaultWorkspace(Workspace.Identifier?)
since the `preferences.selectedWorkspaceId` is optional. In `SettingsReducer` line 88 we have the need for the optional associated value. Should I `guard` for nil `preferences.selectedWorkspaceId` before setting `state.multiOptionSetting` in `SettingsReducer`?

2020-09-01 05:34 UTC, Odrakir commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
It happens in Xcode 12, you can fix it by writing the case like this: `case nil, .some(.none):`

2020-09-01 05:44 UTC, Odrakir commented on Modules/Settings/Settings/Common/SettingsState.swift
> +    case defaultWorkspace(Workspace.Identifier?)
Yeah, I think it makes sense to guard agains that, if there's no default workspace we show an alert and the user should never get this far.

2020-09-01 06:09 UTC, Odrakir commented on Podfile
> +    # The following line converts the acknowledgements.markdown to html to show in the the lincens view in app settings
I'm saying we won't ever remember that's there. Why are we doing this on compile time anyway? Why don't we just embed the html?

2020-09-01 06:11 UTC, Odrakir requested changes
Check my answers

2020-09-01 09:32 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
Will try this when I get home but the nil case may be something new not available in xcode 11

2020-09-01 09:35 UTC, sofokli1 commented on Podfile
> +    # The following line converts the acknowledgements.markdown to html to show in the the lincens view in app settings
This is not compile time. Only when running pod install and similar commands. Which is the right time since that is when the new pods and their licenses are added. We went with this approach because no one will remember to update the licenses manually.

2020-09-01 09:53 UTC, Odrakir commented on Modules/Settings/Settings/Common/SettingsSelector.swift
>      case .none, .some(.none):
It is, I tried.

2020-09-01 09:54 UTC, Odrakir commented on Podfile
> +    # The following line converts the acknowledgements.markdown to html to show in the the lincens view in app settings
Yeah, not compile time, my bad.

2020-09-01 15:42 UTC, sofokli1 commented on Modules/Settings/Settings/Common/SettingsState.swift
> +    case defaultWorkspace(Workspace.Identifier?)
I added the guard but since there is no value, the ws setting will crash the app. Will leave it like this until we are done with the sync and stuff.

2020-09-02 08:38 UTC, Odrakir approved these changes

2020-09-02 09:23 UTC, merged