Add LinkSsoEffect
toggl/ios pull request #719
Opened 2020-09-02 12:28 UTC by sofokli1

## Info
### Summary
Mainly adds the request and the effect to call the request. creates a couple of actions to handle the response of the request. And some tests.

### Relationships
Closes #638

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Commit by commit

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑

2020-09-03 07:20 UTC, sofokli1 commented on Modules/Assets/Assets/Base.lproj/Localizable.strings
> +"invalidConfirmationCodeSSOException" = "Invalid or expired confirmation code";
ref #715

2020-09-03 11:04 UTC, Odrakir requested changes

2020-09-03 11:04 UTC, Odrakir commented on Modules/Networking/Networking/URLSessionExtension.swift
> +                        let result = try endpoint.parse(data)
I'm not sure if we should be trying to parse the data if there was an error. Why not just return the raw data?

2020-09-03 11:04 UTC, Odrakir commented on Modules/Onboarding/Onboarding/SSOLink/SSOLinkReducer.swift
> +        case .setSSOLinkResult:
What's with the string? We don't need it?

2020-09-03 11:24 UTC, sofokli1 commented on Modules/Networking/Networking/URLSessionExtension.swift
> +                        let result = try endpoint.parse(data)
that is how it is done in the old app https://github.com/toggl/mobileapp/pull/7519/files#r439433938

2020-09-03 14:23 UTC, Odrakir commented on Modules/Networking/Networking/URLSessionExtension.swift
> +                        let result = try endpoint.parse(data)
It's doing it right before doing the string comparison, which is what I'm saying.

2020-09-03 16:03 UTC, sofokli1 commented on Modules/Onboarding/Onboarding/SSOLink/SSOLinkReducer.swift
> +        case .setSSOLinkResult:
no we don't, will fix

2020-09-03 16:07 UTC, sofokli1 commented on Modules/Networking/Networking/URLSessionExtension.swift
> +                        let result = try endpoint.parse(data)
ok I see, will return the raw data. was thinking also to remove the `Int` from `wrongStatus(Int, HTTPURLResponse?, Any?)` since it is part of the response anyways. what do you think?

2020-09-03 16:08 UTC, sofokli1 commented on Modules/API/API/API.swift
> +        let endpoint: Endpoint<String> = createEntityEndpoint(path: String("me/enable_sso?email=\(email)&confirmation_code=\(confirmationCode)"))
will take a deeper look at this. first time touching aurora network code

2020-09-03 16:56 UTC, sofokli1 commented on Modules/API/API/API.swift
> +        let endpoint: Endpoint<String> = createEntityEndpoint(path: String("me/enable_sso?email=\(email)&confirmation_code=\(confirmationCode)"))
Should I do any type of encoding to the email value before putting git in the query dict?

2020-09-03 17:00 UTC, sofokli1 commented on Modules/API/APITests/UserAPITests.swift
> +        XCTAssert((loginURL + "/enable_sso?email=some@email.com&confirmation_code=someComfirmationCode") == mockURLSession.requestUrl
I am open to suggestion to better do write this

2020-09-04 13:28 UTC, Odrakir commented on Modules/Onboarding/Onboarding/SSOLink/SSOLinkReducer.swift
> +        case .setSSOLinkResult:
But then why is the endpoint returning a string? I think you have to create a Endpoint<Void> instead

2020-09-04 13:29 UTC, Odrakir commented on Modules/Networking/Networking/URLSessionExtension.swift
> +                        let result = try endpoint.parse(data)
You are right about removing the Int, yeah

2020-09-04 14:44 UTC, Odrakir approved these changes

2020-09-04 14:48 UTC, merged