Refactor database for transactions
toggl/ios pull request #733
Opened 2020-09-10 10:50 UTC by Odrakir

## Info
This PR makes some changes to the DB so it's easy to perform transactions. It also removes the dependency on Rx, moving that to the Repository in the future if needed.

### Technical considerations
This is basically about performing multiple DB operations tied to a single background context, for that I had to move some code around.

There's also a semaphore in place so we can't do two writing operations at the same time. Reading should be fine.

### Relationships
Closes #136 

## Repository health

### Pull Request checklist
- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Commit history is simple, ask me any doubts about Core Data code.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🚫 I want to add some more tests

2020-09-10 12:06 UTC, sofokli1 requested changes
Overall looks good, just a few points

2020-09-10 12:06 UTC, sofokli1 commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +    func testMultipleOperations() {
the format we agreed to follow but not a big deal if you don't feel like changing

2020-09-10 12:06 UTC, sofokli1 commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +                    // try db.workspaces.insert(entity: workspace)
🔥,  other one above

2020-09-10 12:06 UTC, sofokli1 commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +                    print("in", error)
is this needed?

2020-09-10 12:06 UTC, sofokli1 commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +            print("out", error)
same question?

2020-09-10 13:38 UTC, Odrakir commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +        container.persistentStoreDescriptions = [description]
I'm not sure I understand. What are we missing?

2020-09-11 10:57 UTC, sofokli1 commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +        container.persistentStoreDescriptions = [description]
what the blog post is saying is that if we have any `cascading deletes` it is better to use
```
let description = NSPersistentStoreDescription()
description.url = URL(fileURLWithPath: "/dev/null")
container.persistentStoreDescriptions = [description]
```
since the in `NSInMemoryStoreType` does not support `cascading deletes`.

> when using in-memory store, you will find that certain features like cascading deletes might not work as expected. These features appear to rely on features from the default storage (SQLite) that are not available to an in-memory store.

2020-09-11 10:57 UTC, sofokli1 approved these changes
other than this comment https://github.com/toggl/ios/pull/733#discussion_r486969861 it looks good

2020-09-11 10:59 UTC, Odrakir commented on Dependencies/Database/Tests/DatabaseTests/TransactionTests.swift
> +        container.persistentStoreDescriptions = [description]
I'll take a note to look into this in the future. Right now I'm not even sure if we should have cascading deletes at all.

2020-09-11 10:59 UTC, merged