Third-party sign up
toggl/ios pull request #745
Opened 2020-09-22 14:37 UTC by dshr

## Info

### Summary
This PR completes the third party login/signup flow, adding the sign up part.

### Relationships
Closes #645 
Closes #646

## Repository health

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

## Reviewing

### Pointers
Commit by commit should do it.

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations

## Merge permissions
Go for it!

2020-09-23 11:31 UTC, Odrakir requested changes
Some things. Also, check the linter.

2020-09-23 11:31 UTC, Odrakir commented on Dependencies/API/Sources/API/API.swift
> +                                 timezone: String) -> Single<User> {
Change style
```suggestion
    public func thirdPartySignUp(
        token: AuthToken,
        fullName: String,
        termsAccepted: Bool,
        countryId: Int,
        timezone: String
    ) -> Single<User> {
```

2020-09-23 11:31 UTC, Odrakir commented on Dependencies/API/Sources/API/API.swift
> +            path += "?app_name=toggl_mobile"
Endpoint constructor takes a query parameter you can use to add that

2020-09-23 11:31 UTC, Odrakir commented on Dependencies/Onboarding/Sources/Onboarding/Common/OnboardingState.swift
> +
I hate this... but I can't think of a better way to do it right now 🤔

2020-09-23 11:31 UTC, Odrakir commented on Dependencies/API/Sources/API/Protocols/UserAPI.swift
> +                                 timezone: String) -> Single<User>
Alignment
```suggestion
    func thirdPartySignUp(token: AuthToken,
                          fullName: String,
                          termsAccepted: Bool,
                          countryId: Int,
                          timezone: String) -> Single<User>
```

2020-09-23 11:31 UTC, Odrakir commented on Dependencies/Onboarding/Sources/Onboarding/ThirdPartyAuth/ThirdPartyAuthReducer.swift
> +    return Reducer<OnboardingState, ThirdPartyAuthAction>.combine(
Since you are adding a couple of properties to state, wouldn't it make more sense for this reducer to have it's own substate instead of accessing OnboardingState completely?

2020-09-23 15:36 UTC, dshr commented on Dependencies/Onboarding/Sources/Onboarding/Common/OnboardingState.swift
> +
Yeah, this one is ugly, but `||` don't work in `guard case let`s properly :(

2020-09-23 16:15 UTC, dshr commented on Dependencies/Onboarding/Sources/Onboarding/ThirdPartyAuth/ThirdPartyAuthReducer.swift
> +    return Reducer<OnboardingState, ThirdPartyAuthAction>.combine(
I'm not sure how pulling back the Terms Of Service reducer would work then, since we can only get actions for child states, and the `TermsOfServiceState` is a child of `OnboardingState` atm. I don't really want to duplicate a state in two places, feels weird to me.

2020-09-29 09:37 UTC, Odrakir approved these changes

2020-09-30 07:04 UTC, merged